/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CssDemo1: typeof import('./src/components/css-demo1.vue')['default']
    Demo1: typeof import('./src/components/Demo1.vue')['default']
    Demo2: typeof import('./src/components/Demo2.vue')['default']
    Demo3: typeof import('./src/components/Demo3.vue')['default']
    Demo4: typeof import('./src/components/css-demo1.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GoBang: typeof import('./src/components/GoBang.vue')['default']
    Guide: typeof import('./src/components/Guide.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
